const { image } = require('./helpers');

const productsPart1 = [
  {
    categorySlug: 'laptops',
    name: 'Apple MacBook Air 15 M3',
    slug: 'apple-macbook-air-15-m3',
    sku: 'LAP-MBA15-M3-512',
    brand: 'Apple',
    shortDescription: 'Thin 15-inch laptop with the M3 chip and all-day battery life.',
    description: 'The MacBook Air 15 with Apple M3 balances portability, battery life, and strong day-to-day performance for creators, students, and hybrid teams.',
    price: 1699,
    compareAtPrice: 1799,
    stockQuantity: 20,
    lowStockThreshold: 4,
    warranty: '1 year limited warranty',
    searchKeywords: 'apple, macbook, laptop, m3, ultrabook',
    isFeatured: true,
    images: [image('mba15-m3-main'), image('mba15-m3-side')],
    features: ['Apple M3 chip', '15.3-inch Liquid Retina display', '18-hour battery life', 'Silent fanless design'],
    specifications: [
      { key: 'Processor', value: 'Apple M3' },
      { key: 'Memory', value: '16GB unified memory' },
      { key: 'Storage', value: '512GB SSD' },
      { key: 'Display', value: '15.3-inch Liquid Retina' },
    ],
  },
  {
    categorySlug: 'laptops',
    name: 'Dell XPS 14 OLED',
    slug: 'dell-xps-14-oled',
    sku: 'LAP-XPS14-OLED-1TB',
    brand: 'Dell',
    shortDescription: 'Premium creator laptop with a bright OLED panel and Intel Core Ultra power.',
    description: 'The XPS 14 OLED is built for design, coding, and travel with a refined chassis, strong battery, and a sharp 3.2K OLED display.',
    price: 2199,
    compareAtPrice: 2349,
    stockQuantity: 12,
    lowStockThreshold: 3,
    warranty: '1 year onsite support',
    searchKeywords: 'dell, xps, creator laptop, oled',
    isFeatured: true,
    images: [image('xps14-oled-main'), image('xps14-oled-open')],
    features: ['3.2K OLED touchscreen', 'Intel Core Ultra 7', 'NVIDIA RTX 4050 graphics', 'Premium CNC aluminum body'],
    specifications: [
      { key: 'Processor', value: 'Intel Core Ultra 7 155H' },
      { key: 'Memory', value: '32GB LPDDR5x' },
      { key: 'Storage', value: '1TB NVMe SSD' },
      { key: 'Graphics', value: 'NVIDIA GeForce RTX 4050' },
    ],
  },
  {
    categorySlug: 'laptops',
    name: 'ASUS ROG Zephyrus G14',
    slug: 'asus-rog-zephyrus-g14',
    sku: 'LAP-ROG-G14-4070',
    brand: 'ASUS',
    shortDescription: 'Compact gaming laptop with a bright 14-inch Nebula display.',
    description: 'The ROG Zephyrus G14 delivers premium portability with serious gaming performance, strong thermals, and a fast high-resolution panel.',
    price: 1999,
    compareAtPrice: 2149,
    stockQuantity: 9,
    lowStockThreshold: 3,
    warranty: '1 year global warranty',
    searchKeywords: 'asus, rog, gaming laptop, 14 inch',
    isFeatured: false,
    images: [image('rog-g14-main'), image('rog-g14-keyboard')],
    features: ['14-inch Nebula OLED display', 'RTX 4070 graphics', 'Ryzen 9 processor', 'Portable magnesium chassis'],
    specifications: [
      { key: 'Processor', value: 'AMD Ryzen 9 8945HS' },
      { key: 'Memory', value: '32GB LPDDR5x' },
      { key: 'Storage', value: '1TB SSD' },
      { key: 'Graphics', value: 'NVIDIA GeForce RTX 4070' },
    ],
  },
  {
    categorySlug: 'laptops',
    name: 'Lenovo Legion Pro 5i',
    slug: 'lenovo-legion-pro-5i',
    sku: 'LAP-LEGION5I-4060',
    brand: 'Lenovo',
    shortDescription: 'High-value gaming laptop with strong thermals and a fast QHD panel.',
    description: 'The Legion Pro 5i is a balanced pick for gamers and power users who want excellent frame rates, a sharp screen, and dependable cooling.',
    price: 1799,
    compareAtPrice: 1949,
    stockQuantity: 14,
    lowStockThreshold: 4,
    warranty: '1 year premium care',
    searchKeywords: 'lenovo, legion, gaming laptop, qhd',
    isFeatured: false,
    images: [image('legion-5i-main'), image('legion-5i-open')],
    features: ['16-inch 240Hz QHD display', 'RTX 4060 graphics', 'Legion ColdFront cooling', 'Full-size RGB keyboard'],
    specifications: [
      { key: 'Processor', value: 'Intel Core i7-14650HX' },
      { key: 'Memory', value: '16GB DDR5' },
      { key: 'Storage', value: '1TB SSD' },
      { key: 'Graphics', value: 'NVIDIA GeForce RTX 4060' },
    ],
  },
  {
    categorySlug: 'smartphones',
    name: 'Apple iPhone 15 Pro Max',
    slug: 'apple-iphone-15-pro-max',
    sku: 'PHN-IP15PM-256',
    brand: 'Apple',
    shortDescription: 'Titanium flagship iPhone with a 5x telephoto lens and USB-C.',
    description: 'The iPhone 15 Pro Max pairs Apple silicon, a bright ProMotion display, and a premium titanium frame with one of the best mobile camera systems on the market.',
    price: 1399,
    compareAtPrice: 1499,
    stockQuantity: 24,
    lowStockThreshold: 5,
    warranty: '1 year Apple warranty',
    searchKeywords: 'iphone, apple, flagship, ios, pro max',
    isFeatured: true,
    images: [image('iphone15pm-main'), image('iphone15pm-camera')],
    features: ['A17 Pro chip', '5x telephoto camera', '6.7-inch ProMotion display', 'USB-C connectivity'],
    specifications: [
      { key: 'Display', value: '6.7-inch Super Retina XDR' },
      { key: 'Storage', value: '256GB' },
      { key: 'Camera', value: '48MP main plus 5x telephoto' },
      { key: 'Battery', value: 'Up to 29 hours video playback' },
    ],
  },
  {
    categorySlug: 'smartphones',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    sku: 'PHN-GS24U-256',
    brand: 'Samsung',
    shortDescription: 'Large Android flagship with S Pen support and a 200MP camera.',
    description: 'The Galaxy S24 Ultra is built for power users with a versatile camera system, vivid display, and Samsung productivity features anchored by the S Pen.',
    price: 1349,
    compareAtPrice: 1449,
    stockQuantity: 18,
    lowStockThreshold: 4,
    warranty: '1 year Samsung warranty',
    searchKeywords: 'samsung, galaxy, ultra, android, s pen',
    isFeatured: true,
    images: [image('s24ultra-main'), image('s24ultra-back')],
    features: ['Integrated S Pen', '200MP adaptive camera', 'Galaxy AI features', 'Armor aluminum frame'],
    specifications: [
      { key: 'Display', value: '6.8-inch Dynamic AMOLED 2X' },
      { key: 'Storage', value: '256GB' },
      { key: 'Processor', value: 'Snapdragon 8 Gen 3' },
      { key: 'Battery', value: '5000mAh' },
    ],
  },
  {
    categorySlug: 'smartphones',
    name: 'Google Pixel 8 Pro',
    slug: 'google-pixel-8-pro',
    sku: 'PHN-PXL8P-128',
    brand: 'Google',
    shortDescription: 'Camera-first Android phone with useful AI features and clean software.',
    description: 'The Pixel 8 Pro focuses on computational photography, clean Android, and helpful AI-powered experiences that improve search, editing, and everyday productivity.',
    price: 999,
    compareAtPrice: 1099,
    stockQuantity: 16,
    lowStockThreshold: 4,
    warranty: '1 year Google warranty',
    searchKeywords: 'google, pixel, android, camera phone',
    isFeatured: false,
    images: [image('pixel8pro-main'), image('pixel8pro-side')],
    features: ['Google Tensor G3', 'Advanced computational photography', 'Seven years of software support', 'Bright LTPO display'],
    specifications: [
      { key: 'Display', value: '6.7-inch LTPO OLED' },
      { key: 'Storage', value: '128GB' },
      { key: 'Camera', value: '50MP main plus 48MP telephoto' },
      { key: 'Battery', value: '5050mAh' },
    ],
  },
  {
    categorySlug: 'smartphones',
    name: 'OnePlus 12',
    slug: 'oneplus-12',
    sku: 'PHN-OP12-256',
    brand: 'OnePlus',
    shortDescription: 'Fast Android flagship with strong battery life and rapid charging.',
    description: 'The OnePlus 12 is a performance-focused flagship that blends quick charging, a smooth AMOLED display, and flagship-level responsiveness at a sharper price point.',
    price: 899,
    compareAtPrice: 949,
    stockQuantity: 22,
    lowStockThreshold: 5,
    warranty: '1 year OnePlus warranty',
    searchKeywords: 'oneplus, android, flagship, fast charging',
    isFeatured: false,
    images: [image('oneplus12-main'), image('oneplus12-back')],
    features: ['100W fast charging', 'Snapdragon 8 Gen 3', '50W wireless charging', 'Hasselblad camera tuning'],
    specifications: [
      { key: 'Display', value: '6.82-inch LTPO AMOLED' },
      { key: 'Storage', value: '256GB' },
      { key: 'Camera', value: '50MP triple camera system' },
      { key: 'Battery', value: '5400mAh' },
    ],
  },
  {
    categorySlug: 'audio',
    name: 'Sony WH-1000XM5',
    slug: 'sony-wh-1000xm5',
    sku: 'AUD-SONY-WH1000XM5',
    brand: 'Sony',
    shortDescription: 'Reference noise-canceling headphones with rich sound and all-day comfort.',
    description: 'Sony WH-1000XM5 remains a top over-ear travel and work companion with class-leading noise cancellation, excellent call quality, and warm balanced sound.',
    price: 399,
    compareAtPrice: 449,
    stockQuantity: 28,
    lowStockThreshold: 6,
    warranty: '1 year Sony warranty',
    searchKeywords: 'sony, noise cancelling, headphones, travel',
    isFeatured: true,
    images: [image('sony-xm5-main'), image('sony-xm5-fold')],
    features: ['Industry-leading ANC', '30-hour battery life', 'Multipoint Bluetooth', 'Premium microphone array'],
    specifications: [
      { key: 'Type', value: 'Over-ear wireless headphones' },
      { key: 'Battery', value: 'Up to 30 hours' },
      { key: 'Connectivity', value: 'Bluetooth 5.2' },
      { key: 'Weight', value: '250 grams' },
    ],
  },
  {
    categorySlug: 'audio',
    name: 'Apple AirPods Pro 2',
    slug: 'apple-airpods-pro-2',
    sku: 'AUD-AIRPODS-PRO2',
    brand: 'Apple',
    shortDescription: 'Compact earbuds with adaptive audio and strong noise cancellation.',
    description: 'AirPods Pro 2 bring better noise control, improved microphones, and seamless Apple ecosystem pairing to a very portable everyday audio package.',
    price: 249,
    compareAtPrice: 279,
    stockQuantity: 34,
    lowStockThreshold: 8,
    warranty: '1 year Apple warranty',
    searchKeywords: 'airpods, apple, earbuds, anc',
    isFeatured: true,
    images: [image('airpods-pro2-main'), image('airpods-pro2-case')],
    features: ['Adaptive audio', 'Conversation awareness', 'USB-C charging case', 'Find My support'],
    specifications: [
      { key: 'Type', value: 'True wireless earbuds' },
      { key: 'Battery', value: 'Up to 6 hours plus case' },
      { key: 'Chip', value: 'Apple H2' },
      { key: 'Charging', value: 'USB-C and MagSafe' },
    ],
  },
  {
    categorySlug: 'audio',
    name: 'Sonos Era 100',
    slug: 'sonos-era-100',
    sku: 'AUD-SONOS-ERA100',
    brand: 'Sonos',
    shortDescription: 'Smart bookshelf speaker with room-filling sound and easy multi-room audio.',
    description: 'The Sonos Era 100 is a flexible smart speaker for home setups with stereo sound, voice control, and straightforward integration into larger Sonos systems.',
    price: 249,
    compareAtPrice: 279,
    stockQuantity: 17,
    lowStockThreshold: 4,
    warranty: '1 year Sonos warranty',
    searchKeywords: 'sonos, speaker, smart audio, home',
    isFeatured: false,
    images: [image('sonos-era100-main'), image('sonos-era100-side')],
    features: ['Trueplay tuning', 'Wi-Fi and Bluetooth', 'Stereo acoustic design', 'Voice control ready'],
    specifications: [
      { key: 'Type', value: 'Wireless smart speaker' },
      { key: 'Connectivity', value: 'Wi-Fi 6 and Bluetooth 5.0' },
      { key: 'Inputs', value: 'USB-C line in adapter supported' },
      { key: 'Voice', value: 'Sonos Voice Control and Alexa' },
    ],
  },
];

module.exports = {
  productsPart1,
};
