const { image } = require('./helpers');

const productsPart2 = [
  {
    categorySlug: 'gaming',
    name: 'PlayStation 5 Slim',
    slug: 'playstation-5-slim',
    sku: 'GAM-PS5-SLIM',
    brand: 'Sony',
    shortDescription: 'Compact PS5 console with fast loading and immersive DualSense controls.',
    description: 'The PS5 Slim keeps the same fast SSD and strong console performance in a smaller chassis that fits cleanly into living room and bedroom setups.',
    price: 549,
    compareAtPrice: 599,
    stockQuantity: 11,
    lowStockThreshold: 3,
    warranty: '1 year Sony warranty',
    searchKeywords: 'playstation, ps5, console, gaming',
    isFeatured: true,
    images: [image('ps5-slim-main'), image('ps5-slim-side')],
    features: ['Ultra-fast SSD', 'DualSense haptics', '4K gaming support', 'Ray tracing support'],
    specifications: [
      { key: 'Storage', value: '1TB SSD' },
      { key: 'Resolution', value: 'Up to 4K 120Hz' },
      { key: 'Audio', value: 'Tempest 3D AudioTech' },
      { key: 'Connectivity', value: 'Wi-Fi 6 and Ethernet' },
    ],
  },
  {
    categorySlug: 'gaming',
    name: 'Xbox Series X',
    slug: 'xbox-series-x',
    sku: 'GAM-XBOX-SERIESX',
    brand: 'Microsoft',
    shortDescription: 'High-performance console built for smooth frame rates and Game Pass.',
    description: 'Xbox Series X offers strong 4K gaming performance, fast resume features, and an ecosystem that is especially attractive for Game Pass subscribers.',
    price: 529,
    compareAtPrice: 579,
    stockQuantity: 13,
    lowStockThreshold: 3,
    warranty: '1 year Microsoft warranty',
    searchKeywords: 'xbox, series x, console, game pass',
    isFeatured: false,
    images: [image('xbox-seriesx-main'), image('xbox-seriesx-front')],
    features: ['Quick Resume', '1TB NVMe SSD', 'Game Pass ready', '4K gaming support'],
    specifications: [
      { key: 'Storage', value: '1TB custom NVMe SSD' },
      { key: 'Resolution', value: 'Up to 4K 120Hz' },
      { key: 'CPU', value: 'Custom AMD Zen 2' },
      { key: 'GPU', value: 'Custom AMD RDNA 2' },
    ],
  },
  {
    categorySlug: 'gaming',
    name: 'Nintendo Switch OLED',
    slug: 'nintendo-switch-oled',
    sku: 'GAM-SWITCH-OLED',
    brand: 'Nintendo',
    shortDescription: 'Portable console with a brighter OLED screen and flexible play modes.',
    description: 'The Switch OLED is ideal for relaxed and social gaming thanks to its vivid handheld screen, docked TV mode, and broad first-party game library.',
    price: 349,
    compareAtPrice: 379,
    stockQuantity: 19,
    lowStockThreshold: 4,
    warranty: '1 year Nintendo warranty',
    searchKeywords: 'nintendo, switch, oled, handheld console',
    isFeatured: false,
    images: [image('switch-oled-main'), image('switch-oled-dock')],
    features: ['7-inch OLED display', 'Handheld and docked play', 'Wide kickstand', 'Enhanced speakers'],
    specifications: [
      { key: 'Storage', value: '64GB internal storage' },
      { key: 'Display', value: '7-inch OLED' },
      { key: 'Modes', value: 'Handheld, tabletop, and docked' },
      { key: 'Battery', value: '4.5 to 9 hours' },
    ],
  },
  {
    categorySlug: 'accessories',
    name: 'Anker 737 Power Bank',
    slug: 'anker-737-power-bank',
    sku: 'ACC-ANKER-737',
    brand: 'Anker',
    shortDescription: 'High-capacity power bank with laptop-class 140W USB-C charging.',
    description: 'The Anker 737 is a premium travel charger and power bank designed for creators and commuters who want to top up phones, tablets, and even larger laptops on the move.',
    price: 159,
    compareAtPrice: 179,
    stockQuantity: 31,
    lowStockThreshold: 6,
    warranty: '18-month Anker warranty',
    searchKeywords: 'anker, power bank, usb c, charging',
    isFeatured: false,
    images: [image('anker-737-main'), image('anker-737-display')],
    features: ['140W USB-C charging', '24000mAh capacity', 'Smart digital display', 'Laptop charging support'],
    specifications: [
      { key: 'Capacity', value: '24000mAh' },
      { key: 'Output', value: 'Up to 140W' },
      { key: 'Ports', value: '2 USB-C plus 1 USB-A' },
      { key: 'Weight', value: '630 grams' },
    ],
  },
  {
    categorySlug: 'accessories',
    name: 'Logitech MX Master 3S',
    slug: 'logitech-mx-master-3s',
    sku: 'ACC-MXMASTER-3S',
    brand: 'Logitech',
    shortDescription: 'Ergonomic wireless productivity mouse with quiet clicks and precision tracking.',
    description: 'MX Master 3S is a go-to productivity mouse for multi-device work, creative software navigation, and long editing sessions that benefit from the thumb wheel and ergonomic shape.',
    price: 109,
    compareAtPrice: 129,
    stockQuantity: 36,
    lowStockThreshold: 8,
    warranty: '1 year Logitech warranty',
    searchKeywords: 'logitech, mouse, productivity, wireless',
    isFeatured: false,
    images: [image('mxmaster3s-main'), image('mxmaster3s-side')],
    features: ['Quiet clicks', '8K DPI tracking', 'MagSpeed scrolling', 'Multi-device pairing'],
    specifications: [
      { key: 'Connection', value: 'Bluetooth or Logi Bolt' },
      { key: 'Battery', value: 'Up to 70 days' },
      { key: 'Sensor', value: '8000 DPI Darkfield' },
      { key: 'Compatibility', value: 'Windows, macOS, Linux' },
    ],
  },
  {
    categorySlug: 'accessories',
    name: 'Samsung T9 Portable SSD 2TB',
    slug: 'samsung-t9-portable-ssd-2tb',
    sku: 'ACC-SAMSUNG-T9-2TB',
    brand: 'Samsung',
    shortDescription: 'Fast portable SSD for creators moving large video and photo projects.',
    description: 'The Samsung T9 is a rugged, high-speed external drive designed for video teams, photographers, and developers who regularly move large working files between devices.',
    price: 229,
    compareAtPrice: 259,
    stockQuantity: 23,
    lowStockThreshold: 5,
    warranty: '5 year Samsung warranty',
    searchKeywords: 'samsung, ssd, storage, usb c',
    isFeatured: true,
    images: [image('samsung-t9-main'), image('samsung-t9-cable')],
    features: ['USB 3.2 Gen 2x2 speed', 'Durable rubber finish', 'Hardware encryption support', 'Creator-ready transfer speeds'],
    specifications: [
      { key: 'Capacity', value: '2TB' },
      { key: 'Speed', value: 'Up to 2000MB/s' },
      { key: 'Connector', value: 'USB-C' },
      { key: 'Security', value: 'AES 256-bit encryption' },
    ],
  },
  {
    categorySlug: 'accessories',
    name: 'Belkin 3-in-1 MagSafe Stand',
    slug: 'belkin-3-in-1-magsafe-stand',
    sku: 'ACC-BELKIN-MAG3IN1',
    brand: 'Belkin',
    shortDescription: 'Premium dock that charges iPhone, AirPods, and Apple Watch together.',
    description: 'This Belkin stand is a reliable bedside or desk charger for Apple users who want a cleaner setup and fast MagSafe charging in one footprint.',
    price: 149,
    compareAtPrice: 169,
    stockQuantity: 15,
    lowStockThreshold: 4,
    warranty: '2 year Belkin warranty',
    searchKeywords: 'belkin, magsafe, apple charger, dock',
    isFeatured: false,
    images: [image('belkin-3in1-main'), image('belkin-3in1-angle')],
    features: ['Official MagSafe charging', 'Apple Watch fast charge', 'Desk-friendly footprint', 'Cable management built in'],
    specifications: [
      { key: 'Charging', value: '15W MagSafe for iPhone' },
      { key: 'Compatibility', value: 'iPhone, AirPods, Apple Watch' },
      { key: 'Finish', value: 'Soft-touch premium stand' },
      { key: 'Power', value: 'Included wall adapter' },
    ],
  },
  {
    categorySlug: 'smart-home',
    name: 'Google Nest Hub Max',
    slug: 'google-nest-hub-max',
    sku: 'HOME-NEST-HUBMAX',
    brand: 'Google',
    shortDescription: 'Smart display for recipes, video calls, cameras, and home control.',
    description: 'Nest Hub Max works well in kitchens and family spaces with a large display, Google Assistant, and easy smart-home controls for connected routines.',
    price: 249,
    compareAtPrice: 279,
    stockQuantity: 10,
    lowStockThreshold: 3,
    warranty: '1 year Google warranty',
    searchKeywords: 'google, nest, smart home, display',
    isFeatured: false,
    images: [image('nest-hub-max-main'), image('nest-hub-max-kitchen')],
    features: ['10-inch smart display', 'Built-in camera', 'Google Assistant', 'Smart home dashboard'],
    specifications: [
      { key: 'Display', value: '10-inch HD touch display' },
      { key: 'Audio', value: 'Stereo speakers with subwoofer' },
      { key: 'Voice', value: 'Google Assistant' },
      { key: 'Connectivity', value: 'Wi-Fi and Bluetooth' },
    ],
  },
  {
    categorySlug: 'smart-home',
    name: 'Amazon Echo Show 8',
    slug: 'amazon-echo-show-8',
    sku: 'HOME-ECHO-SHOW8',
    brand: 'Amazon',
    shortDescription: 'Alexa smart display for music, routines, and household communication.',
    description: 'Echo Show 8 is an approachable home display for routines, calls, and quick media controls, especially for Alexa-first households.',
    price: 179,
    compareAtPrice: 199,
    stockQuantity: 13,
    lowStockThreshold: 3,
    warranty: '1 year Amazon warranty',
    searchKeywords: 'amazon, alexa, smart display, echo show',
    isFeatured: false,
    images: [image('echo-show8-main'), image('echo-show8-side')],
    features: ['8-inch HD display', 'Alexa voice control', 'Smart home routines', 'Compact bedside size'],
    specifications: [
      { key: 'Display', value: '8-inch HD touch display' },
      { key: 'Camera', value: '13MP center camera' },
      { key: 'Voice', value: 'Alexa' },
      { key: 'Connectivity', value: 'Wi-Fi and Bluetooth' },
    ],
  },
  {
    categorySlug: 'wearables',
    name: 'Apple Watch Series 9',
    slug: 'apple-watch-series-9',
    sku: 'WEAR-AW-S9-45',
    brand: 'Apple',
    shortDescription: 'Refined smartwatch for fitness, notifications, and everyday health tracking.',
    description: 'Apple Watch Series 9 covers notifications, workouts, and wellness metrics in a polished package that works best for iPhone users.',
    price: 429,
    compareAtPrice: 459,
    stockQuantity: 21,
    lowStockThreshold: 5,
    warranty: '1 year Apple warranty',
    searchKeywords: 'apple watch, smartwatch, wearable, health',
    isFeatured: true,
    images: [image('apple-watch-s9-main'), image('apple-watch-s9-strap')],
    features: ['Double Tap gesture', 'Always-on display', 'Heart rate notifications', 'Workout tracking'],
    specifications: [
      { key: 'Case Size', value: '45mm' },
      { key: 'Connectivity', value: 'GPS plus Bluetooth' },
      { key: 'Battery', value: 'Up to 18 hours' },
      { key: 'Water Resistance', value: '50 meters' },
    ],
  },
  {
    categorySlug: 'wearables',
    name: 'Samsung Galaxy Watch 6 Classic',
    slug: 'samsung-galaxy-watch-6-classic',
    sku: 'WEAR-GW6-CLASSIC',
    brand: 'Samsung',
    shortDescription: 'Smartwatch with rotating bezel, sleep insights, and a traditional look.',
    description: 'Galaxy Watch 6 Classic combines the familiar rotating bezel with strong health tracking and Android-friendly smart features.',
    price: 399,
    compareAtPrice: 429,
    stockQuantity: 18,
    lowStockThreshold: 4,
    warranty: '1 year Samsung warranty',
    searchKeywords: 'samsung, galaxy watch, smartwatch, android',
    isFeatured: false,
    images: [image('galaxy-watch6-main'), image('galaxy-watch6-side')],
    features: ['Rotating bezel', 'Sleep coaching', 'Body composition tracking', 'Wear OS support'],
    specifications: [
      { key: 'Case Size', value: '47mm' },
      { key: 'Display', value: 'Super AMOLED' },
      { key: 'Battery', value: 'Up to 40 hours' },
      { key: 'Water Resistance', value: '5ATM plus IP68' },
    ],
  },
];

module.exports = {
  productsPart2,
};
