const coupons = [
  {
    code: 'TECHZONE10',
    description: '10 percent off on orders above 100 dollars.',
    discountType: 'percent',
    discountValue: 10,
    minOrderValue: 100,
    maxDiscountAmount: 250,
    startsAt: '2025-01-01 00:00:00',
    endsAt: '2027-12-31 23:59:59',
    usageLimit: 500,
    isActive: true,
  },
  {
    code: 'LAPTOP150',
    description: 'Flat 150 dollars off on laptop orders above 1500 dollars.',
    discountType: 'fixed',
    discountValue: 150,
    minOrderValue: 1500,
    maxDiscountAmount: null,
    startsAt: '2025-01-01 00:00:00',
    endsAt: '2027-12-31 23:59:59',
    usageLimit: 200,
    isActive: true,
  },
  {
    code: 'AUDIO15',
    description: '15 percent off premium audio orders above 150 dollars.',
    discountType: 'percent',
    discountValue: 15,
    minOrderValue: 150,
    maxDiscountAmount: 120,
    startsAt: '2025-01-01 00:00:00',
    endsAt: '2027-12-31 23:59:59',
    usageLimit: 300,
    isActive: true,
  },
];

const carts = [
  {
    email: 'aisha.khan@example.com',
    items: [
      { sku: 'ACC-ANKER-737', quantity: 1 },
      { sku: 'ACC-MXMASTER-3S', quantity: 1 },
    ],
  },
  {
    email: 'priya.singh@example.com',
    items: [
      { sku: 'AUD-SONY-WH1000XM5', quantity: 1 },
      { sku: 'HOME-NEST-HUBMAX', quantity: 1 },
    ],
  },
  {
    email: 'daniel.lee@example.com',
    items: [
      { sku: 'LAP-XPS14-OLED-1TB', quantity: 1 },
    ],
  },
];

const wishlists = [
  {
    email: 'rohan.mehta@example.com',
    skus: ['PHN-IP15PM-256', 'ACC-SAMSUNG-T9-2TB', 'WEAR-AW-S9-45'],
  },
  {
    email: 'neha.verma@example.com',
    skus: ['PHN-GS24U-256', 'AUD-AIRPODS-PRO2', 'HOME-ECHO-SHOW8'],
  },
  {
    email: 'maria.garcia@example.com',
    skus: ['LAP-ROG-G14-4070', 'GAM-PS5-SLIM', 'ACC-BELKIN-MAG3IN1'],
  },
];

const orders = [
  {
    orderNumber: 'TZ-10001',
    email: 'rohan.mehta@example.com',
    addressLabel: 'Apartment',
    status: 'delivered',
    paymentMethod: 'card',
    paymentStatus: 'paid',
    couponCode: 'TECHZONE10',
    trackingNumber: 'TRK-TZ-10001',
    placedAt: '2026-01-10 10:15:00',
    deliveredAt: '2026-01-16 18:30:00',
    notes: 'Customer requested evening delivery.',
    items: [
      { sku: 'PHN-IP15PM-256', quantity: 1 },
      { sku: 'ACC-ANKER-737', quantity: 1 },
    ],
  },
  {
    orderNumber: 'TZ-10002',
    email: 'aisha.khan@example.com',
    addressLabel: 'Home',
    status: 'delivered',
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    couponCode: 'AUDIO15',
    trackingNumber: 'TRK-TZ-10002',
    placedAt: '2026-02-05 13:40:00',
    deliveredAt: '2026-02-09 15:00:00',
    notes: '',
    items: [
      { sku: 'AUD-SONY-WH1000XM5', quantity: 1 },
      { sku: 'AUD-AIRPODS-PRO2', quantity: 1 },
    ],
  },
  {
    orderNumber: 'TZ-10003',
    email: 'priya.singh@example.com',
    addressLabel: 'Home',
    status: 'shipped',
    paymentMethod: 'card',
    paymentStatus: 'paid',
    couponCode: '',
    trackingNumber: 'TRK-TZ-10003',
    placedAt: '2026-03-01 09:25:00',
    deliveredAt: null,
    notes: 'Ship with signature required.',
    items: [{ sku: 'LAP-MBA15-M3-512', quantity: 1 }],
  },
  {
    orderNumber: 'TZ-10004',
    email: 'arjun.iyer@example.com',
    addressLabel: 'Home',
    status: 'confirmed',
    paymentMethod: 'cod',
    paymentStatus: 'pending',
    couponCode: '',
    trackingNumber: '',
    placedAt: '2026-03-12 16:05:00',
    deliveredAt: null,
    notes: '',
    items: [
      { sku: 'GAM-PS5-SLIM', quantity: 1 },
      { sku: 'GAM-SWITCH-OLED', quantity: 1 },
    ],
  },
  {
    orderNumber: 'TZ-10005',
    email: 'neha.verma@example.com',
    addressLabel: 'Studio',
    status: 'cancelled',
    paymentMethod: 'card',
    paymentStatus: 'refunded',
    couponCode: 'TECHZONE10',
    trackingNumber: '',
    placedAt: '2026-03-18 11:10:00',
    cancelledAt: '2026-03-19 08:10:00',
    deliveredAt: null,
    notes: 'Customer changed device preference.',
    items: [{ sku: 'PHN-GS24U-256', quantity: 1 }],
  },
  {
    orderNumber: 'TZ-10006',
    email: 'daniel.lee@example.com',
    addressLabel: 'Home',
    status: 'processing',
    paymentMethod: 'paypal',
    paymentStatus: 'paid',
    couponCode: 'LAPTOP150',
    trackingNumber: '',
    placedAt: '2026-03-25 19:30:00',
    deliveredAt: null,
    notes: 'Gift wrap requested.',
    items: [
      { sku: 'LAP-XPS14-OLED-1TB', quantity: 1 },
      { sku: 'ACC-SAMSUNG-T9-2TB', quantity: 1 },
    ],
  },
  {
    orderNumber: 'TZ-10007',
    email: 'maria.garcia@example.com',
    addressLabel: 'Loft',
    status: 'delivered',
    paymentMethod: 'card',
    paymentStatus: 'paid',
    couponCode: '',
    trackingNumber: 'TRK-TZ-10007',
    placedAt: '2026-04-02 08:45:00',
    deliveredAt: '2026-04-06 12:10:00',
    notes: '',
    items: [
      { sku: 'WEAR-AW-S9-45', quantity: 1 },
      { sku: 'ACC-BELKIN-MAG3IN1', quantity: 1 },
    ],
  },
  {
    orderNumber: 'TZ-10008',
    email: 'aisha.khan@example.com',
    addressLabel: 'Home',
    status: 'delivered',
    paymentMethod: 'card',
    paymentStatus: 'paid',
    couponCode: '',
    trackingNumber: 'TRK-TZ-10008',
    placedAt: '2026-04-05 17:20:00',
    deliveredAt: '2026-04-08 10:25:00',
    notes: '',
    items: [
      { sku: 'HOME-NEST-HUBMAX', quantity: 1 },
      { sku: 'WEAR-GW6-CLASSIC', quantity: 1 },
    ],
  },
];

const reviews = [
  {
    email: 'rohan.mehta@example.com',
    sku: 'PHN-IP15PM-256',
    rating: 5,
    title: 'Excellent daily driver',
    comment: 'The camera and battery life are excellent, and the USB-C port finally simplifies charging on my desk.',
    createdAt: '2026-01-18 09:30:00',
  },
  {
    email: 'rohan.mehta@example.com',
    sku: 'ACC-ANKER-737',
    rating: 4,
    title: 'Great for travel',
    comment: 'It is heavy, but it charges both my phone and laptop quickly when I am on flights.',
    createdAt: '2026-01-18 09:42:00',
  },
  {
    email: 'aisha.khan@example.com',
    sku: 'AUD-SONY-WH1000XM5',
    rating: 5,
    title: 'Perfect for remote work',
    comment: 'Noise cancellation is outstanding during meetings and the comfort is good enough for long workdays.',
    createdAt: '2026-02-11 11:00:00',
  },
  {
    email: 'aisha.khan@example.com',
    sku: 'AUD-AIRPODS-PRO2',
    rating: 4,
    title: 'Very convenient',
    comment: 'Pairing is instant and the adaptive audio works well, though I still prefer over-ear headphones for longer sessions.',
    createdAt: '2026-02-11 11:15:00',
  },
  {
    email: 'priya.singh@example.com',
    sku: 'LAP-MBA15-M3-512',
    rating: 5,
    title: 'Fast and quiet',
    comment: 'It stays cool, looks premium, and handles design work better than I expected from such a thin machine.',
    createdAt: '2026-03-14 13:45:00',
  },
  {
    email: 'arjun.iyer@example.com',
    sku: 'GAM-PS5-SLIM',
    rating: 5,
    title: 'Instantly upgraded my setup',
    comment: 'Games load very quickly and the compact design fits much better in my TV cabinet than the older model.',
    createdAt: '2026-03-25 20:10:00',
  },
  {
    email: 'maria.garcia@example.com',
    sku: 'WEAR-AW-S9-45',
    rating: 4,
    title: 'Strong health features',
    comment: 'Great for notifications and training sessions, and the brighter display is noticeable outdoors.',
    createdAt: '2026-04-07 09:05:00',
  },
  {
    email: 'aisha.khan@example.com',
    sku: 'HOME-NEST-HUBMAX',
    rating: 4,
    title: 'Useful kitchen companion',
    comment: 'We use it daily for timers, music, and checking our front door camera feed without pulling out our phones.',
    createdAt: '2026-04-08 19:25:00',
  },
];

module.exports = {
  coupons,
  carts,
  wishlists,
  orders,
  reviews,
};
