const { image } = require('./helpers');

const users = [
  {
    name: 'Admin User',
    email: 'admin@techzone.com',
    password: 'Admin@1234',
    role: 'admin',
    phone: '+91 9876543210',
    avatarUrl: image('admin-user'),
    addresses: [
      {
        label: 'Office',
        fullName: 'Admin User',
        phone: '+91 9876543210',
        line1: '42 Nehru Place',
        line2: 'Suite 605',
        city: 'New Delhi',
        state: 'Delhi',
        postalCode: '110019',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Aisha Khan',
    email: 'aisha.khan@example.com',
    password: 'User@1234',
    role: 'customer',
    phone: '+91 9988776655',
    avatarUrl: image('aisha-khan'),
    addresses: [
      {
        label: 'Home',
        fullName: 'Aisha Khan',
        phone: '+91 9988776655',
        line1: '17 Residency Road',
        line2: '',
        city: 'Bengaluru',
        state: 'Karnataka',
        postalCode: '560025',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Rohan Mehta',
    email: 'rohan.mehta@example.com',
    password: 'User@1234',
    role: 'customer',
    phone: '+91 9811223344',
    avatarUrl: image('rohan-mehta'),
    addresses: [
      {
        label: 'Apartment',
        fullName: 'Rohan Mehta',
        phone: '+91 9811223344',
        line1: '91 Linking Road',
        line2: 'Flat 1204',
        city: 'Mumbai',
        state: 'Maharashtra',
        postalCode: '400050',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Priya Singh',
    email: 'priya.singh@example.com',
    password: 'User@1234',
    role: 'customer',
    phone: '+91 9797979797',
    avatarUrl: image('priya-singh'),
    addresses: [
      {
        label: 'Home',
        fullName: 'Priya Singh',
        phone: '+91 9797979797',
        line1: '228 Banjara Hills',
        line2: '',
        city: 'Hyderabad',
        state: 'Telangana',
        postalCode: '500034',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Arjun Iyer',
    email: 'arjun.iyer@example.com',
    password: 'User@1234',
    role: 'customer',
    phone: '+91 9665511223',
    avatarUrl: image('arjun-iyer'),
    addresses: [
      {
        label: 'Home',
        fullName: 'Arjun Iyer',
        phone: '+91 9665511223',
        line1: '8 Boat Club Road',
        line2: 'Block B',
        city: 'Chennai',
        state: 'Tamil Nadu',
        postalCode: '600028',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Neha Verma',
    email: 'neha.verma@example.com',
    password: 'User@1234',
    role: 'customer',
    phone: '+91 9554411220',
    avatarUrl: image('neha-verma'),
    addresses: [
      {
        label: 'Studio',
        fullName: 'Neha Verma',
        phone: '+91 9554411220',
        line1: '14 Park Street',
        line2: 'Unit 7C',
        city: 'Kolkata',
        state: 'West Bengal',
        postalCode: '700016',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Daniel Lee',
    email: 'daniel.lee@example.com',
    password: 'User@1234',
    role: 'customer',
    phone: '+1 415 555 0148',
    avatarUrl: image('daniel-lee'),
    addresses: [
      {
        label: 'Home',
        fullName: 'Daniel Lee',
        phone: '+1 415 555 0148',
        line1: '480 Mission Street',
        line2: 'Apt 1402',
        city: 'San Francisco',
        state: 'California',
        postalCode: '94105',
        country: 'United States',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Maria Garcia',
    email: 'maria.garcia@example.com',
    password: 'User@1234',
    role: 'customer',
    phone: '+1 206 555 0130',
    avatarUrl: image('maria-garcia'),
    addresses: [
      {
        label: 'Loft',
        fullName: 'Maria Garcia',
        phone: '+1 206 555 0130',
        line1: '112 Pine Street',
        line2: 'Floor 6',
        city: 'Seattle',
        state: 'Washington',
        postalCode: '98101',
        country: 'United States',
        isDefault: true,
      },
    ],
  },
];

module.exports = {
  users,
};
